//
//  Levels.swift
//  MonkeysWar
//
//  Created by Alberto Saltarelli on 17/09/22.
//

import Foundation

enum Levels {
    static let day1 = Level(houseHP: 100, monkeys: [
        Monkey(node: Monkeys.flo(), delay: 0, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 6, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 6, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.gaga(), delay: 6, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 6, spawn: .right),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.gaga(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.gaga(), delay: 1, spawn: .left),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .left),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.gaga(), delay: 0.5, spawn: .right),
        Monkey(node: Monkeys.gaga(), delay: 1, spawn: .right),
        Monkey(node: Monkeys.flo(), delay: 0.5, spawn: .left)
    ])
}
